### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by Pocker88** [BukuBukuChagma/recaptcha-solver-using-image-classification#1]
Sir, can you help me ...how use it on Android (Kivi browser)..?!?

**Comment by BukuBukuChagma** [comment]
Hi @Pocker88 . Sorry but you cannot run this on android.

**Comment by Pocker88** [comment]
Sir can you explain how use it on PC (Tampermonkey Google Chrome) ???

**Comment by BukuBukuChagma** [comment]
> Sir can you explain how use it on PC (Tampermonkey Google Chrome) ???

@Pocker88 This one doesn't work well as it was for testing purposes only. I'm currently working on a better one and it should be uploaded in a day or two. I'll also upload a full on guide on how to use that. I'll ping you when its up

**Comment by Pocker88** [comment]
> > Sir can you explain how use it on PC (Tampermonkey Google Chrome) ???
> 
> @Pocker88 This one doesn't work well as it was for testing purposes only. I'm currently working on a better one and it should be uploaded in a day or two. I'll also upload a full on guide on how to use that. I'll ping you when its up

Thank 🙏 you so much Sir!!!

**Comment by BukuBukuChagma** [comment]
@Pocker88 There you go : https://github.com/BukuBukuChagma/Google-ReCaptcha-V2-Solver

**Comment by Pocker88** [comment]
@BukuBukuChagma Thank you so much) but ... Iam 0 at Python... Iam know only user scripts for Tampermonkey. But thanks 🙏😊
